config/routes.rb
Blog::Application.routes.draw do
  devise_for :users
  resources :profiles

  get "welcome/index"

  root 'welcome#index'

  

    resources :articles do

        collection do
         get 'to_be_approved'
       end
       member do
         get 'approve_article'
        end

      resources :comments
    end

       

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
        can [:read, :create, :new], [Article, Comment]
        can [:edit, :update, :destroy], Article, :user_id => user.id
        can [:edit, :update, :destroy], Comment, :user_id => user.id


        #can :manage, Article, :user_id => user.id

       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	belongs_to :user

	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   	has_many :comments, dependent: :destroy
   	has_many :articles, dependent: :destroy
   	has_one :profile, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to root_url, :alert => exception.message }
    end
  end	  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, :except => [:index]
    load_and_authorize_resource
	def index
	    @articles = Article.where(:aprrove => true)
	
	end

	def new
		@article = Article.new
	end

  def edit
  @article = Article.find(params[:id])
  end

	def create
		@article = current_user.articles.create(article_params)
  		if @article.save

  			redirect_to @article
  		else
  			render 'new'
  		end
  end

  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    
    if @article.destroy
      redirect_to articles_path
    else
      redirect_to root_path
    end
  end


  	def show
  		 @article = Article.find(params[:id])

  	end

    def to_be_approved
      @articles = Article.where(:aprrove => false)

    end

    def approve_article
      article = Article.find(params[:id])
      article.aprrove = true
      article.save
      ArticleMailer.publish_article_email(current_user).deliver

      redirect_to  to_be_approved_articles_path
    end

  	private
  def article_params
    params.require(:article).permit(:title, :text, :aprrove)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  before_action :authenticate_user!, :except => [:index]
  load_and_authorize_resource

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    CommentMailer.publish_comment_email(@article.user_id,current_user).deliver
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :user_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, :except => [:index]


  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :occupation, :date_of_birth)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 <%if current_user.admin?%>
  <%= f.hidden_field :aprrove, :value => true%>
 <% end %>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      
      <% if can? :update, article %>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <%end%>

      <% if can? :destroy, article %>
        <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <%end%>

    </tr>
  <% end %>
</table>

<%= link_to 'New article', new_article_path %>

app/views/articles/new.html.erb
<h1>hello to articles/new </h1>


<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Back', articles_path %>
<%= link_to 'Edit', edit_article_path(@article) %>

app/views/articles/to_be_approved.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Approve', approve_article_article_path(article) %></td>
      <td><%#= link_to 'Delete', article_path(article),
             method: :delete,
           data: { confirm: 'Are you sure?' } %></td>
           <% if can? :destroy, article %>
        <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <%end%>

    </tr>
  <% end %>
</table>

<%= link_to 'New article', new_article_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/_user_header.html.erb
<ul class="nav nav-pills pull-right">
  <% if user_signed_in? %>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-narrow">
  <div class="masthead">
    <%= render 'layouts/user_header' %>
    <h3 class="muted"><%= link_to "SimpleDevise", root_path %></h3>
    <h5 class="muted">A demo of using SimpleDB with Devise</h5>
  </div>
  <hr />
  <%= yield %>
</div>

</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for @profile, :html => { :class => "form-horizontal profile" } do |f| %>

  <% if @profile.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :occupation, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :occupation, :class => 'form-control' %>
    </div>
    <%=f.error_span(:occupation) %>
  </div>
  <div class="form-group">
    <%= f.label :date_of_birth, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
<%= date_select :date_of_birth, :date_of_birth , :class => 'datepicker' %>    </div>
    <%=f.error_span(:date_of_birth) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                profiles_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/profiles/edit.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/profiles/index.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:occupation) %></th>
      <th><%= model_class.human_attribute_name(:date_of_birth) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= link_to profile.id, profile_path(profile) %></td>
        <td><%= profile.name %></td>
        <td><%= profile.occupation %></td>
        <td><%= profile.date_of_birth %></td>
        <td><%=l profile.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_profile_path(profile), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      profile_path(profile),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_profile_path,
            :class => 'btn btn-primary' %>

app/views/profiles/new.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/profiles/show.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @profile.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:occupation) %>:</strong></dt>
  <dd><%= @profile.occupation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date_of_birth) %>:</strong></dt>
  <dd><%= @profile.date_of_birth %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              profiles_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_profile_path(@profile), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              profile_path(@profile),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <% if user_signed_in? %>
    <h1>Welcome back, trusted user!</h1>
    <%= current_user.admin?%>
    <p class="lead">
      <h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>

    </p>
    <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => 'btn btn-large btn-danger' %>
  <% else %>
    <h1>Welcome, new user!</h1>
    <p class="lead">
      You must sign in or sign up before you can access our super sweet,
      top secret content.
    </p>
    <div class="row">
      <div class="col-lg-3 col-md-3 col-xs-6">
        <%= link_to "Sign In", new_user_session_path, :class => "btn btn-success" %>
      </div>
      
      <div class="col-lg-3 col-md-3 col-xs-6">
        <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>